import './globals.css'
import { dir } from 'i18next'
import { Inter } from 'next/font/google'
import BottomNavBar from '~/ui/BottomNavBar'
import { languages } from '~/i18n/setting'

const inter = Inter({ subsets: ['latin'] })

export async function generateStaticParams() {
  return languages.map((lang) => ({ lang }))
}

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
  params: {
    lang
  },
}: {
  children: React.ReactNode,
  params: { lang: string },
}) {
  return (
    <html lang={lang}  dir={dir(lang)}>
      <head>
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
        <link rel="manifest" href="/site.webmanifest"></link>
        <script src="/serviceWorkerRegister.js" defer></script>
      </head>
      <body className={`${inter.className} h-screen min-h-screen max-h-screen w-full fcc-between`}>
        <div className='flex-1 w-full'>
          {children}
        </div>
        <div className='flex-0 w-full bg-white shadow'>
          <BottomNavBar />
        </div>
      </body>
    </html >
  )
}
