import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import BottomNavBar from '~/ui/BottomNavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
        <link rel="manifest" href="/site.webmanifest"></link>
        <script src="/serviceWorkerRegister.js" defer></script>
      </head>
      <body className={`${inter.className} h-screen min-h-screen max-h-screen fcc-between`}>
        <div className='flex-1'>
          {children}
        </div>
        <div className='flex-0 w-full bg-white shadow'>
          <BottomNavBar />
        </div>
      </body>
    </html >
  )
}
